import { describe, it, expect } from "vitest";
import {
  CUBE_ARG_IDX,
  DIM_ARG_IDX,
  PROCESS_ARG_IDX,
  ELEM_ARG_IDX,
  SUBSET_ARG_IDX,
  FUNC_RE,
} from "../../src/lib/callgraph/referenceIndex.js";

// Pinned literal expectations for the arg-index tables that drive TI reference
// extraction. Captured from the original KNOWN_SIGNATURES derivation (vscode-tm1-ti
// tiSignatures.ts) so any table rewrite must reproduce them exactly, order included.

const EXPECTED_CUBE_ARG_IDX: [string, number][] = [
  ["cellgetn", 0],
  ["cellgets", 0],
  ["cellputn", 1],
  ["cellputs", 1],
  ["cellexists", 0],
  ["cellisundefined", 0],
  ["cellisrule", 0],
  ["cellisupdateable", 0],
  ["cubeattrn", 0],
  ["cubeattrs", 0],
  ["cubeattrnl", 0],
  ["cubeattrsl", 0],
  ["cubeattrputn", 1],
  ["cubeattrputs", 1],
  ["viewattrn", 0],
  ["viewattrs", 0],
  ["viewattrnl", 0],
  ["viewattrsl", 0],
  ["viewattrputn", 1],
  ["viewattrputs", 1],
  ["cubecreate", 0],
  ["viewcreate", 0],
  ["cubedelete", 0],
  ["cubedestroy", 0],
  ["cubeexists", 0],
  ["tabdim", 0],
  ["cubecleardata", 0],
  ["cubesetlogchanges", 0],
  ["cubegetlogchanges", 0],
  ["cubegetn", 0],
  ["cubegets", 0],
  ["cubeputn", 1],
  ["cubeputs", 1],
  ["ruledestroy", 0],
  ["ruleloadfromfile", 0],
  ["viewcreatebymdx", 0],
  ["viewdelete", 0],
  ["viewexists", 0],
  ["viewzero", 0],
  ["viewconstruct", 0],
  ["viewcolumndimensionset", 0],
  ["viewrowdimensionset", 0],
  ["viewtitledimensionset", 0],
  ["viewtitleelementset", 0],
  ["viewsubsetassign", 0],
  ["viewextractskipcalcsset", 0],
  ["viewextractskiprulevaluesset", 0],
  ["viewextractskipzeroesset", 0],
  ["viewextractskipconsolidatedvaluesset", 0],
  ["viewgetn", 0],
  ["viewgets", 0],
  ["viewputn", 1],
  ["viewputs", 1],
  ["datasourceodbocubename", 0],
  ["addinfocuberestriction", 0],
  ["batchcellincrement", 1],
  ["cubedatareservationacquire", 0],
  ["cubedatareservationget", 0],
  ["cubedatareservationgetconflicts", 0],
  ["cubedatareservationrelease", 0],
  ["cubedatareservationreleaseall", 0],
  ["cubesavedata", 0],
  ["cubesetconnparams", 0],
  ["cubeunload", 0],
  ["lockoff", 0],
  ["lockon", 0],
  ["cubedracquire", 0],
  ["cubedrget", 0],
  ["cubedrgetconflicts", 0],
  ["cubedrrelease", 0],
  ["cubedrreleaseall", 0],
  ["addcubedependency", 0],
  ["cubedimensioncountget", 0],
  ["cubeprocessfeeders", 0],
  ["cuberuleappend", 0],
  ["cuberuledestroy", 0],
  ["cubetimelastupdated", 0],
  ["cellsecuritycubecreate", 0],
  ["cellsecuritycubedestroy", 0],
  ["cellincrementn", 1],
  ["cellputproportionalspread", 1],
  ["metadataallrollups", 0],
  ["metadatarollups", 0],
  ["metadatarollupsall", 0],
  ["viewcolumndimensionget", 0],
  ["viewcolumndimensionsetget", 0],
  ["viewdestroy", 0],
  ["viewmdxactivate", 0],
  ["viewmdxdeactivate", 0],
  ["viewmdxget", 0],
  ["viewmdxset", 0],
  ["viewrowdimensionget", 0],
  ["viewrowdimensionsetget", 0],
  ["viewstructcompact", 0],
  ["viewstructupdate", 0],
  ["viewsubsetget", 0],
  ["viewzerosuppressionget", 0],
  ["viewzerosuppressionset", 0],
  ["viewzeroout", 0],
];

const EXPECTED_DIM_ARG_IDX: [string, number][] = [
  ["dimsiz", 0],
  ["dimnm", 0],
  ["dimix", 0],
  ["dtype", 0],
  ["dnlev", 0],
  ["dnxt", 0],
  ["elpar", 0],
  ["elparn", 0],
  ["ellev", 0],
  ["elcomp", 0],
  ["elcompn", 0],
  ["elweight", 0],
  ["elisanc", 0],
  ["elisdesc", 0],
  ["attrs", 0],
  ["attrn", 0],
  ["attributeput", 1],
  ["attrputs", 1],
  ["attrputn", 1],
  ["elementsecurityput", 1],
  ["attributeget", 0],
  ["dimensionattrn", 0],
  ["dimensionattrs", 0],
  ["dimensionattrnl", 0],
  ["dimensionattrsl", 0],
  ["dimensionattrputn", 1],
  ["dimensionattrputs", 1],
  ["subsetattrn", 0],
  ["subsetattrs", 0],
  ["subsetattrnl", 0],
  ["subsetattrsl", 0],
  ["subsetattrputn", 1],
  ["subsetattrputs", 1],
  ["attrdelete", 0],
  ["attrinsert", 0],
  ["attrnl", 0],
  ["attrsl", 0],
  ["elementattrnl", 0],
  ["elementattrsl", 0],
  ["elementattrputn", 1],
  ["elementattrputs", 1],
  ["dimensioncreate", 0],
  ["elementinsert", 0],
  ["subsetcreate", 1],
  ["subsetelementadd", 1],
  ["dimensiondestroy", 0],
  ["dimensionexists", 0],
  ["dimensiondeleteallelements", 0],
  ["dimensionelementinsert", 0],
  ["dimensionelementdelete", 0],
  ["dimensionelementmove", 0],
  ["dimensionelementcount", 0],
  ["dimensionelementexists", 0],
  ["dimensionelementcomponentadd", 0],
  ["dimensionelementcomponentdelete", 0],
  ["dimensionsortorder", 0],
  ["elementcount", 0],
  ["elementdelete", 0],
  ["elementexists", 0],
  ["elementindex", 0],
  ["elementname", 0],
  ["elementlevel", 0],
  ["elementtype", 0],
  ["elementparent", 0],
  ["elementparentcount", 0],
  ["elementcomponent", 0],
  ["elementcomponentcount", 0],
  ["elementweight", 0],
  ["elementattrn", 0],
  ["elementattrs", 0],
  ["elementattrinsert", 0],
  ["elementattrdelete", 0],
  ["hierarchyattrn", 0],
  ["hierarchyattrs", 0],
  ["hierarchyattrnl", 0],
  ["hierarchyattrsl", 0],
  ["hierarchyattrputn", 1],
  ["hierarchyattrputs", 1],
  ["elispar", 0],
  ["elisstr", 0],
  ["elisattr", 0],
  ["hierarchycreate", 0],
  ["hierarchyexists", 0],
  ["hierarchyelementcount", 0],
  ["hierarchyelementinsert", 0],
  ["hierarchyelementdelete", 0],
  ["hierarchyelementcomponentadd", 0],
  ["hierarchyname", 0],
  ["hierarchydestroy", 0],
  ["hierarchydeleteallelements", 0],
  ["hierarchydeleteelements", 0],
  ["hierarchycontainsallleaves", 0],
  ["hierarchyhasorphanedleaves", 0],
  ["hierarchytimelastupdated", 0],
  ["hierarchyupdatedirect", 0],
  ["hierarchysortorder", 0],
  ["hierarchytopelementinsert", 0],
  ["hierarchytopelementinsertdirect", 0],
  ["hierarchyelementexists", 0],
  ["hierarchyelementdeletedirect", 0],
  ["hierarchyelementinsertdirect", 0],
  ["hierarchyelementprincipalname", 0],
  ["hierarchyelementcomponentadddirect", 0],
  ["hierarchyelementcomponentdelete", 0],
  ["hierarchyelementcomponentdeletedirect", 0],
  ["hierarchyelementsecurityget", 0],
  ["hierarchyelementsecurityput", 1],
  ["hierarchysubsetcreate", 0],
  ["hierarchysubsetdestroy", 0],
  ["hierarchysubsetexists", 0],
  ["hierarchysubsetdeleteallelements", 0],
  ["hierarchysubsetelementinsert", 0],
  ["hierarchysubsetelementdelete", 0],
  ["hierarchysubsetelementexists", 0],
  ["hierarchysubsetelementgetindex", 0],
  ["hierarchysubsetgetelementname", 0],
  ["hierarchysubsetgetsize", 0],
  ["hierarchysubsetisallset", 0],
  ["hierarchysubsetmdxget", 0],
  ["hierarchysubsetmdxset", 0],
  ["hierarchysubsetaliasget", 0],
  ["hierarchysubsetaliasset", 0],
  ["hierarchysubsetattrn", 0],
  ["hierarchysubsetattrs", 0],
  ["hierarchysubsetattrnl", 0],
  ["hierarchysubsetattrsl", 0],
  ["hierarchysubsetattrputn", 1],
  ["hierarchysubsetattrputs", 1],
  ["hierarchysubsetattrinsert", 0],
  ["hierarchysubsetattrdelete", 0],
  ["attributecreate", 0],
  ["attributedelete", 0],
  ["attributeexists", 0],
  ["subsetdelete", 1],
  ["subsetelementdelete", 1],
  ["subsetexists", 1],
  ["subsetgetelementname", 1],
  ["subsetgetsize", 1],
  ["subsettoset", 1],
  ["viewcolumndimensionset", 2],
  ["viewrowdimensionset", 2],
  ["viewtitledimensionset", 2],
  ["viewtitleelementset", 2],
  ["viewsubsetassign", 2],
  ["dimensiondeleteelements", 0],
  ["dimensionelementcomponentadddirect", 0],
  ["dimensionelementcomponentdeletedirect", 0],
  ["dimensionelementdeletedirect", 0],
  ["dimensionelementinsertdirect", 0],
  ["dimensionelementprincipalname", 0],
  ["dimensionhierarchycreate", 0],
  ["dimensiontimelastupdated", 0],
  ["dimensiontopelementinsert", 0],
  ["dimensiontopelementinsertdirect", 0],
  ["dimensionupdatedirect", 0],
  ["olapdimensionproperty", 0],
  ["olapelementname", 0],
  ["olapelementnames", 0],
  ["olapmemberproperty", 0],
  ["subsetaliasget", 0],
  ["subsetaliasset", 0],
  ["subsetdeleteallelements", 0],
  ["subsetdestroy", 0],
  ["subsetelementexists", 0],
  ["subsetelementgetindex", 0],
  ["subsetelementinsert", 0],
  ["subsetisallset", 0],
  ["subsetmdxget", 0],
  ["subsetmdxset", 0],
  ["viewsubsetget", 2],
  ["levelcount", 0],
];

const EXPECTED_PROCESS_ARG_IDX: [string, number][] = [
  ["executeprocess", 0],
  ["runprocess", 0],
];

const EXPECTED_ELEM_ARG_IDX: [string, number][] = [
  ["dimix", 1],
  ["dtype", 1],
  ["dnxt", 1],
  ["elpar", 1],
  ["elparn", 1],
  ["ellev", 1],
  ["elcomp", 1],
  ["elcompn", 1],
  ["elisanc", 1],
  ["elisdesc", 1],
  ["attrs", 1],
  ["attrn", 1],
  ["attributeput", 2],
  ["attrputs", 2],
  ["attrputn", 2],
  ["elementsecurityput", 2],
  ["attributeget", 1],
  ["attrnl", 1],
  ["attrsl", 1],
  ["elementattrnl", 1],
  ["elementattrsl", 1],
  ["elementattrputn", 2],
  ["elementattrputs", 2],
  ["elementinsert", 3],
  ["subsetelementadd", 2],
  ["dimensionelementinsert", 2],
  ["dimensionelementdelete", 1],
  ["dimensionelementmove", 1],
  ["dimensionelementexists", 1],
  ["elementdelete", 2],
  ["elementexists", 2],
  ["elementindex", 2],
  ["elementlevel", 2],
  ["elementtype", 2],
  ["elementparent", 2],
  ["elementparentcount", 2],
  ["elementcomponent", 2],
  ["elementcomponentcount", 2],
  ["elementattrn", 1],
  ["elementattrs", 1],
  ["elispar", 1],
  ["elisstr", 1],
  ["elisattr", 1],
  ["hierarchyelementinsert", 3],
  ["hierarchyelementdelete", 2],
  ["hierarchytopelementinsert", 3],
  ["hierarchytopelementinsertdirect", 3],
  ["hierarchyelementexists", 2],
  ["hierarchyelementdeletedirect", 2],
  ["hierarchyelementinsertdirect", 3],
  ["hierarchyelementprincipalname", 2],
  ["hierarchyelementsecurityget", 2],
  ["hierarchyelementsecurityput", 3],
  ["hierarchysubsetelementinsert", 3],
  ["hierarchysubsetelementdelete", 3],
  ["hierarchysubsetelementexists", 3],
  ["hierarchysubsetelementgetindex", 3],
  ["subsetelementdelete", 2],
  ["viewtitleelementset", 3],
  ["dimensionelementdeletedirect", 1],
  ["dimensionelementinsertdirect", 2],
  ["dimensionelementprincipalname", 1],
  ["dimensiontopelementinsert", 1],
  ["dimensiontopelementinsertdirect", 1],
  ["olapmemberproperty", 1],
  ["subsetelementexists", 2],
  ["subsetelementgetindex", 2],
  ["subsetelementinsert", 2],
];

const EXPECTED_SUBSET_ARG_IDX: [string, number][] = [
  ["subsetattrn", 1],
  ["subsetattrs", 1],
  ["subsetattrnl", 1],
  ["subsetattrsl", 1],
  ["subsetattrputn", 2],
  ["subsetattrputs", 2],
  ["subsetcreate", 0],
  ["subsetelementadd", 0],
  ["hierarchydeleteelements", 2],
  ["hierarchysubsetcreate", 2],
  ["hierarchysubsetdestroy", 2],
  ["hierarchysubsetexists", 2],
  ["hierarchysubsetdeleteallelements", 2],
  ["hierarchysubsetelementinsert", 2],
  ["hierarchysubsetelementdelete", 2],
  ["hierarchysubsetelementexists", 2],
  ["hierarchysubsetelementgetindex", 2],
  ["hierarchysubsetgetelementname", 2],
  ["hierarchysubsetgetsize", 2],
  ["hierarchysubsetisallset", 2],
  ["hierarchysubsetmdxget", 2],
  ["hierarchysubsetmdxset", 2],
  ["hierarchysubsetaliasget", 2],
  ["hierarchysubsetaliasset", 2],
  ["hierarchysubsetattrn", 2],
  ["hierarchysubsetattrs", 2],
  ["hierarchysubsetattrnl", 2],
  ["hierarchysubsetattrsl", 2],
  ["hierarchysubsetattrputn", 3],
  ["hierarchysubsetattrputs", 3],
  ["hierarchysubsetattrinsert", 2],
  ["hierarchysubsetattrdelete", 2],
  ["subsetcreatebymdx", 0],
  ["subsetdelete", 0],
  ["subsetelementdelete", 0],
  ["subsetexists", 0],
  ["subsetgetelementname", 0],
  ["subsetgetsize", 0],
  ["subsettoset", 0],
  ["viewsubsetassign", 3],
  ["datasourcedimensionsubset", 0],
  ["subsetaliasget", 1],
  ["subsetaliasset", 1],
  ["subsetdeleteallelements", 1],
  ["subsetdestroy", 1],
  ["subsetelementexists", 1],
  ["subsetelementgetindex", 1],
  ["subsetelementinsert", 1],
  ["subsetisallset", 1],
  ["subsetmdxget", 1],
  ["subsetmdxset", 1],
];

const EXPECTED_FUNC_RE_SOURCE =
  "\\b(cellgetn|cellgets|cellputn|cellputs|cellexists|cellisundefined|cellisrule|cellisupdateable|cubeattrn|cubeattrs|cubeattrnl|cubeattrsl|cubeattrputn|cubeattrputs|viewattrn|viewattrs|viewattrnl|viewattrsl|viewattrputn|viewattrputs|cubecreate|viewcreate|cubedelete|cubedestroy|cubeexists|tabdim|cubecleardata|cubesetlogchanges|cubegetlogchanges|cubegetn|cubegets|cubeputn|cubeputs|ruledestroy|ruleloadfromfile|viewcreatebymdx|viewdelete|viewexists|viewzero|viewconstruct|viewcolumndimensionset|viewrowdimensionset|viewtitledimensionset|viewtitleelementset|viewsubsetassign|viewextractskipcalcsset|viewextractskiprulevaluesset|viewextractskipzeroesset|viewextractskipconsolidatedvaluesset|viewgetn|viewgets|viewputn|viewputs|datasourceodbocubename|addinfocuberestriction|batchcellincrement|cubedatareservationacquire|cubedatareservationget|cubedatareservationgetconflicts|cubedatareservationrelease|cubedatareservationreleaseall|cubesavedata|cubesetconnparams|cubeunload|lockoff|lockon|cubedracquire|cubedrget|cubedrgetconflicts|cubedrrelease|cubedrreleaseall|addcubedependency|cubedimensioncountget|cubeprocessfeeders|cuberuleappend|cuberuledestroy|cubetimelastupdated|cellsecuritycubecreate|cellsecuritycubedestroy|cellincrementn|cellputproportionalspread|metadataallrollups|metadatarollups|metadatarollupsall|viewcolumndimensionget|viewcolumndimensionsetget|viewdestroy|viewmdxactivate|viewmdxdeactivate|viewmdxget|viewmdxset|viewrowdimensionget|viewrowdimensionsetget|viewstructcompact|viewstructupdate|viewsubsetget|viewzerosuppressionget|viewzerosuppressionset|viewzeroout|dimsiz|dimnm|dimix|dtype|dnlev|dnxt|elpar|elparn|ellev|elcomp|elcompn|elweight|elisanc|elisdesc|attrs|attrn|attributeput|attrputs|attrputn|elementsecurityput|attributeget|dimensionattrn|dimensionattrs|dimensionattrnl|dimensionattrsl|dimensionattrputn|dimensionattrputs|subsetattrn|subsetattrs|subsetattrnl|subsetattrsl|subsetattrputn|subsetattrputs|attrdelete|attrinsert|attrnl|attrsl|elementattrnl|elementattrsl|elementattrputn|elementattrputs|dimensioncreate|elementinsert|subsetcreate|subsetelementadd|dimensiondestroy|dimensionexists|dimensiondeleteallelements|dimensionelementinsert|dimensionelementdelete|dimensionelementmove|dimensionelementcount|dimensionelementexists|dimensionelementcomponentadd|dimensionelementcomponentdelete|dimensionsortorder|elementcount|elementdelete|elementexists|elementindex|elementname|elementlevel|elementtype|elementparent|elementparentcount|elementcomponent|elementcomponentcount|elementweight|elementattrn|elementattrs|elementattrinsert|elementattrdelete|hierarchyattrn|hierarchyattrs|hierarchyattrnl|hierarchyattrsl|hierarchyattrputn|hierarchyattrputs|elispar|elisstr|elisattr|hierarchycreate|hierarchyexists|hierarchyelementcount|hierarchyelementinsert|hierarchyelementdelete|hierarchyelementcomponentadd|hierarchyname|hierarchydestroy|hierarchydeleteallelements|hierarchydeleteelements|hierarchycontainsallleaves|hierarchyhasorphanedleaves|hierarchytimelastupdated|hierarchyupdatedirect|hierarchysortorder|hierarchytopelementinsert|hierarchytopelementinsertdirect|hierarchyelementexists|hierarchyelementdeletedirect|hierarchyelementinsertdirect|hierarchyelementprincipalname|hierarchyelementcomponentadddirect|hierarchyelementcomponentdelete|hierarchyelementcomponentdeletedirect|hierarchyelementsecurityget|hierarchyelementsecurityput|hierarchysubsetcreate|hierarchysubsetdestroy|hierarchysubsetexists|hierarchysubsetdeleteallelements|hierarchysubsetelementinsert|hierarchysubsetelementdelete|hierarchysubsetelementexists|hierarchysubsetelementgetindex|hierarchysubsetgetelementname|hierarchysubsetgetsize|hierarchysubsetisallset|hierarchysubsetmdxget|hierarchysubsetmdxset|hierarchysubsetaliasget|hierarchysubsetaliasset|hierarchysubsetattrn|hierarchysubsetattrs|hierarchysubsetattrnl|hierarchysubsetattrsl|hierarchysubsetattrputn|hierarchysubsetattrputs|hierarchysubsetattrinsert|hierarchysubsetattrdelete|attributecreate|attributedelete|attributeexists|subsetdelete|subsetelementdelete|subsetexists|subsetgetelementname|subsetgetsize|subsettoset|dimensiondeleteelements|dimensionelementcomponentadddirect|dimensionelementcomponentdeletedirect|dimensionelementdeletedirect|dimensionelementinsertdirect|dimensionelementprincipalname|dimensionhierarchycreate|dimensiontimelastupdated|dimensiontopelementinsert|dimensiontopelementinsertdirect|dimensionupdatedirect|olapdimensionproperty|olapelementname|olapelementnames|olapmemberproperty|subsetaliasget|subsetaliasset|subsetdeleteallelements|subsetdestroy|subsetelementexists|subsetelementgetindex|subsetelementinsert|subsetisallset|subsetmdxget|subsetmdxset|levelcount|executeprocess|runprocess)\\s*\\(";

describe("callgraph arg-index tables", () => {
  it("CUBE_ARG_IDX matches the pinned table", () => {
    expect([...CUBE_ARG_IDX.entries()]).toEqual(EXPECTED_CUBE_ARG_IDX);
  });

  it("DIM_ARG_IDX matches the pinned table", () => {
    expect([...DIM_ARG_IDX.entries()]).toEqual(EXPECTED_DIM_ARG_IDX);
  });

  it("PROCESS_ARG_IDX matches the pinned table", () => {
    expect([...PROCESS_ARG_IDX.entries()]).toEqual(EXPECTED_PROCESS_ARG_IDX);
  });

  it("ELEM_ARG_IDX matches the pinned table", () => {
    expect([...ELEM_ARG_IDX.entries()]).toEqual(EXPECTED_ELEM_ARG_IDX);
  });

  it("SUBSET_ARG_IDX matches the pinned table", () => {
    expect([...SUBSET_ARG_IDX.entries()]).toEqual(EXPECTED_SUBSET_ARG_IDX);
  });

  it("FUNC_RE source matches the pinned pattern", () => {
    expect(FUNC_RE.source).toBe(EXPECTED_FUNC_RE_SOURCE);
    expect(FUNC_RE.flags).toBe("gi");
  });
});
